baseURL = "/"
languageCode = "de-DE"
theme = "necct-theme"
title = "NECCT"
[params]
cloudinary_url = "https://res.cloudinary.com/codecentric-ag/image/upload"
default_video = "https://res.cloudinary.com/codecentric-ag/video/upload/v1617027534/necct-io/2021/03/default_video_background_jd9ahe.webm"
[permalinks]
casestudies = "/:slug/"
[[menu.main]]
identifier = "Category 2"
name = "Category 2"
parent = "news"
url = "/news/category2/"
weight = 2
[[menu.main]]
identifier = "Category 1"
name = "Category 1"
parent = "news"
url = "/news/category1/"
weight = 1
[[menu.main]]
identifier = "hello"
name = "CONTACT"
url = "/direction/"
weight = 5
[[menu.main]]
identifier = "news"
name = "WHAT IF"
url = "/news/"
weight = 4
[[menu.main]]
identifier = "necct"
name = "ABOUT"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "casestudies"
name = "CASE STUDIES"
url = "/casestudies/"
weight = 3
[[menu.main]]
identifier = "start"
name = "HOME"
url = "/"
weight = 1
